import _ from 'lodash';

const randomCommonDescriptions = [
  'This crystalline egg almost looks like you could reach into its depths.',
  'Wind gusts around this egg.',
  'You can see the baby dragon curled up inside this translucent egg.',
  'The brilliant blue spots on this egg stand out.',
  'This dull mottled egg blends into the surrounding algae.',
  'This glossy green egg is rather warm.',
  'This delicately patterned egg is sitting in the sunshine.',
  'This egg is surrounded by mysterious, reflective dust.',
  'This drab egg rests far from the water\'s edge.',
  'The vibrant scales on this egg glisten in the sunlight.',
  'This bright egg has a warm shell.',
  'A low hum emanates from this rough egg.',
  'This ashen egg is smooth to the touch.',
  'This egg reminds you of the night sky.',
  'This pleasant egg was placed in the path of a refreshing breeze.',
  'This large egg has a lustrous sheen and appears to be covered in scales.',
  'This light egg is floating in the air.',
  'This egg has a faint green glow around it.',
  'This egg has a black cap.',
  'This egg has a faintly exotic scent.',
  'This egg has a pleasant, musky smell.',
  'This egg is off-white in color and smells a bit like salt.',
  'This egg has a dull metallic luster and is hot to the touch.',
  'This egg shines brilliantly in moonlight, and is covered in red spots.',
  'This egg is covered in thick blue stripes.',
  'This egg has a striking pattern.',
  'This egg is covered in pale blue spots.',
  'This egg is covered in speckles.',
  'This egg smells rather rancid.',
  'This egg is unusually large and heavy.',
  'This mottled red egg almost glows from within.',
  'This egg is hidden by some leaves.',
  'This pink and red egg wobbles occasionally.',
  'This egg makes you feel a bit uneasy.',
  'This translucent egg shines like starlight.',
  'This soft egg was carefully nestled in feathers and snow.',
  'This egg reminds you of the sea.',
  'This icy egg sparkles with frost.',
  'This egg is sitting in a patch of grass and small flowers even though there\'s no sun in the cave.',
  'This egg shines coldly in the moonlight.',
  'This egg is sitting on a cloud.',
  'This egg appears to be covered in scales.',
  'This egg shines like a diamond.',
  'This egg has multiple bands of color on it.',
  'Bright sparks glide across the surface of this egg\'s shell.',
  'Starlight shimmers across this egg\'s iridescent shell.',
  'This egg is really hot.',
  'This egg shakes slightly when taken out of the light.',
  'Cold flames dance across the surface of this egg.',
  'This egg has delicate markings that curl around its shell.',
  'This mottled egg looks positively ancient.',
  'This egg is patterned with an orange flare.',
  'This egg is yellow with orange speckling.',
  'This egg has strange markings on it.',
  'Frost is creeping over this cold egg.',
  'Powerful energy emanates from this egg.',
  'This egg is heavy and rough, as if it were made out of rock.',
  'This egg has bright orange and green markings.',
  'This egg is sitting in a pile of small pebbles.',
  'This egg is sitting in front of the others.',
  'This heavy egg feels slightly warm.',
  'This egg radiates the heat of a fell flame.',
  'This hot egg shakes violently when you touch it.',
  'This shady egg seems to be lurking just out of sight.',
  'This egg has strange markings on it.',
  'This smooth egg has a bright blue stripe on it.',
  'This striped egg is surprisingly heavy.',
  'This egg is hidden in the trees.',
  'This egg is smooth and shiny.',
  'This shiny egg gives off an almost magical aura.',
  'This shimmering egg was hidden far from the others.',
  'This green and silver egg lurks in the shadows, tempting you to steal it.',
  'This red and gold egg sits before the others, almost daring you to grab it.',
  'This egg glows vibrantly in the dark.',
  'This glowing egg seems to tug at your very core.',
  'This scaly egg seems to disappear in the depths.',
  'This egg shines brightly in the sunlight.',
  'The markings on this egg glow brightly in the shadows.',
  'This egg has an orange aura radiating from it.',
  'This egg has washed up on the beach.',
  'This heavy egg has an earthy scent, like freshly-tilled soil.',
  'This egg is hidden behind the others, as if it is shy.',
  'This egg emanates a peculiar smell.',
  'You hear a soft melody as you approach this egg.',
  'This egg is buried in leaf litter.',
  'This egg resembles a glowing stone.',
  'This egg has strange yellow stripes.',
  'This dull purple egg has two bright stripes on it.',
  'This egg appears to be made of limestone.',
  'This egg smells musty, like rotting leaves.',
  'It feels like this egg knew you were coming.',
  'This egg has a velvety texture.',
  'It\'s bright. And pink.',
  'This massive egg is covered with thick plates.',
  'Wow, purple isn\'t a color of egg you expected to see.',
  'Tough ridges line the surface of this rough, mottled egg.',
  'This glassy egg is too hot to hold with your bare hands.',
  'When you tap on this shell, the hatchling inside taps back.',
  'This blue and bronze egg piques your curiosity.',
  'This egg is rather warm.',
  'A cool mountain breeze blows around this egg.',
  'This large egg is a dark crimson color.',
  'This egg was buried in a sand dune.',
  'This egg\'s shell is slippery and clean.',
  'This egg looks like a beautiful blue stone.',
  'Soft chirping sounds are coming from inside the egg.',
  'This egg seems quite harmless.',
  'This egg is covered in mysterious patterns.',
  'The markings on this egg match the weather outside.',
  'This egg has striations marking its rough shell.',
  'This egg appears to be covered in scales.',
  'This striped egg has a rough, ridged texture.',
  'This dark egg has bright flecks that almost seem to move as they catch the light.',
  'This striped egg has a warm glow.',
  'This egg seems to be glowing in spots.',
  'This light egg has very vibrant colors.',
  'This plain blue egg almost seems to float.',
  'This egg has strange markings on it.',
  'This egg has a rough—yet shiny—shell.',
  'This glassy egg has a single stripe on it.',
  'This egg glows from within.',
  'This egg has brightly colored markings on it.',
  'This egg is covered in bright spots.',
  'A red stone is embedded in this egg\'s cold shell.',
  'This egg is heavy and rough, as if it were made out of rock.',
  'This egg is surrounded by fog.',
  'This egg is very large, but light for its size.',
  'This egg has brightly colored markings on it.',
  'A small puddle of condensation has collected under this egg.',
  'This egg is glowing as brightly as the sun.',
  'This egg changes colors in the sunlight.',
  'This egg resembles a glowing stone.',
  'This egg has a very thin shell.',
  'Water glistens on this egg\'s shimmering shell.',
  'This egg is a lush green hue.',
  'This egg has faint markings.',
  'Cold lightning arcs out from this egg\'s shell if you try to touch it.',
  'This egg has vivid red stripes, reminiscent of waves and flames at once.',
  'This brown egg is covered in intricate designs.',
  'This egg is rocking back and forth in a puddle, creating small waves.',
  'This egg smells strongly of turpentine.',
  'There is a thin layer of moisture coating this egg.',
  'An aura of serenity surrounds this iridescent egg.',
  'This egg is sitting in a shallow puddle.',
  'This egg seems to be floating on a puddle.',
  'This egg is slimy and blue.',
  'This egg shakes from time to time, as if it is eager to hatch.',
  'This egg has a very clean look; it\'s completely devoid of dirt and scratches.',
  'This egg is surrounded by beautiful flowers.',
  'This dull egg feels cozily warm.',
  'The air shimmers around this egg, as if from heat.',
  'This heavy egg has a soft, yielding shell.',
  'This egg has raised golden ridges.',
  'This egg is dark with light speckles...or maybe it\'s light with dark speckles?',
  'This opalescent egg shimmers in the moonlight.',
  'This egg can\'t seem to make up its mind what color it is.',
  'This scaled egg is surrounded by the others.',
  'This shiny egg gives you a headache when you get close.',
  'This egg has spots that glow brightly when touched.',
  'This egg glitters oddly in the light.',
  'The surface of this egg is rough and sharp.',
  'This shiny grey egg smells of burnt metal.',
  'This dense, crystalline egg seems dangerously unstable.',
  'A single blue spot marks this egg.',
  'This egg is split down the middle into two colors.',
  'This egg has a winding pattern on it.',
  'This tiny egg is rather light.',
  'This tiny white egg shakes sometimes.',
  'This egg is so tiny you almost didn\'t see it.',
  'This tiny egg is striped and feels coarse.',
  'This egg is tiny and brightly colored.',
  'Crystals are growing around the shell of this little egg.',
  'Grabbing this tiny egg makes you feel reckless.',
  'This tiny egg gives off a colorful glow.',
  'This tiny blue egg gives you a slight shock when you touch it.',
  'This tiny, dark egg fills you with existential dread.',
  'This tiny cobalt egg has a crystalline sheen.',
  'This small egg is engulfed in a cool, purple flame.',
  'This tiny egg smells like the sea.',
  'This tiny glowing egg tempts you to follow its light.',
  'This tiny egg has crazy swirls on it.',
  'This tiny egg is mysterious and dark.',
  'This tiny egg is heavier than you expected.',
  'Shadows flicker wildly around this diminutive egg.',
  'This little egg blends into the sand.',
  'This tiny egg resembles a seed.',
  'This little egg is soft with a few feathers stuck to it.',
  'This tiny egg has a bold red streak on it.',
  'This tiny egg flashes in the sunlight.',
  'This tiny egg shines like a pearl.',
  'Two thin stripes crisscross the shell of this egg.',
  'This striped egg feels moist.',
  'This egg is speckled with rosette-like markings.',
  'This egg is covered in tiny golden scales.',
  'You hear strange noises coming from inside this egg.',
  'This egg displays the colors of both dawn and dusk.',
  'A few bright markings decorate this egg\'s shell.',
  'This egg has strange markings on it.',
  'It almost looks like there are claw marks on this egg.',
  'This striped egg is surprisingly heavy.',
  'This egg displays the colors of both dawn and dusk.',
  'A delicate web-like pattern decorates this egg\'s shell.',
  'This egg has a rough shell.',
  'This smooth green egg looks vaguely familiar.',
];

const rareDescriptions = [
  {
    breed: 'Silver',
    description: 'This egg gives off a beautiful glow.',
  }, {
    breed: 'Gold',
    description: 'This egg is very reflectve, almost metallic-looking.',
  }, {
    breed: 'Staterae',
    description: 'Mana flows like a current through this glassy egg.',
  },
];

export default function getDescriptions() {
  const chosen = _.sampleSize(randomCommonDescriptions, 3).map((description) => ({ breed: 'Common', description }));
  chosen[_.random(0, 2)] = rareDescriptions[_.random(0, 2)];
  return chosen;
}
